### ISSUE TITLE
merge computantis-frontend-demo into this repo?

### ISSUE THREAD

**Issue by kmroz** [TheBlueDotGame/the-accountant#193]
Might be nice to add the frontend to the demo directly in this repository (ie. build an image for it, run it alongside the core and demo services).

What y'all think?

**Comment by bartossh** [comment]
Valid point. I have no preference and for the sake of simplicity, I think this will be a good start.
What do you think about creating a new project in from scratch to create a proper UI?
We can use Angular, Flutter, React or else for that.
